"""
Generates a polished, branded PDF report of a loan prediction result:
decision, confidence, ELRS breakdown (with drawn bar visualisation),
top contributing factors, AI-generated explanation, improvement suggestions,
and an application summary.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (BaseDocTemplate, Frame, HRFlowable, KeepTogether,
                                 NextPageTemplate, PageTemplate, Paragraph,
                                 Spacer, Table, TableStyle)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics import renderPDF

NAVY        = colors.HexColor("#151A34")
VIOLET      = colors.HexColor("#6C4AB6")
VIOLET_LIGHT= colors.HexColor("#EDE7F8")
GREEN       = colors.HexColor("#1E9E6B")
RED         = colors.HexColor("#D64545")
GREY        = colors.HexColor("#6B7280")
LIGHT_BG    = colors.HexColor("#F6F5FB")
BAR_FILL    = colors.HexColor("#6C4AB6")
BAR_EMPTY   = colors.HexColor("#E2E0EF")
AMBER       = colors.HexColor("#D97706")


def _header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(NAVY)
    canvas.rect(0, A4[1] - 2.1 * cm, A4[0], 2.1 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(1.8 * cm, A4[1] - 1.35 * cm, "VittaBodh")
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#C9C3E8"))
    canvas.drawString(1.8 * cm, A4[1] - 1.75 * cm, "Explainable AI Loan Assessment Report")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(A4[0] - 1.8 * cm, A4[1] - 1.35 * cm,
                            datetime.now().strftime("%d %b %Y, %H:%M"))

    canvas.setFillColor(GREY)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawCentredString(A4[0] / 2, 1.0 * cm,
                              "Generated by VittaBodh for informational purposes only, "
                              "not a final lending commitment.")
    canvas.drawRightString(A4[0] - 1.8 * cm, 1.0 * cm, f"Page {doc.page}")
    canvas.restoreState()


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("VBTitle", parent=ss["Heading1"], fontSize=20,
                           textColor=NAVY, spaceAfter=4, fontName="Helvetica-Bold"))
    ss.add(ParagraphStyle("VBSection", parent=ss["Heading2"], fontSize=13,
                           textColor=VIOLET, spaceBefore=14, spaceAfter=6,
                           fontName="Helvetica-Bold"))
    ss.add(ParagraphStyle("VBBody", parent=ss["Normal"], fontSize=10, leading=15,
                           textColor=colors.HexColor("#2B2B38")))
    ss.add(ParagraphStyle("VBMuted", parent=ss["Normal"], fontSize=8.5, leading=12,
                           textColor=GREY))
    ss.add(ParagraphStyle("VBTip", parent=ss["Normal"], fontSize=9.5, leading=14,
                           textColor=colors.HexColor("#2B2B38"), leftIndent=8,
                           spaceAfter=4))
    return ss


def _make_bar_drawing(score, maxv, width=100, height=10):
    """Returns a ReportLab Drawing of a progress bar (no Unicode chars)."""
    d = Drawing(width, height)
    # Background track
    d.add(Rect(0, 2, width, 6, fillColor=BAR_EMPTY, strokeColor=None))
    # Filled portion
    fill_w = max(0, min(1, score / maxv)) * width
    if fill_w > 0:
        d.add(Rect(0, 2, fill_w, 6, fillColor=BAR_FILL, strokeColor=None))
    return d


def _pillar_bar_table(elrs):
    pillars = [
        ("Credit Health",     elrs["credit_health"],     25),
        ("Income & Stability",elrs["income_stability"],  25),
        ("Asset & Collateral",elrs["asset_collateral"],  20),
        ("Debt Burden",       elrs["debt_burden"],       15),
        ("Profile Risk",      elrs["profile_risk"],      15),
    ]
    data = [["Risk Pillar", "Score", "Visual", "Max"]]
    for name, score, maxv in pillars:
        bar = _make_bar_drawing(score, maxv, width=120, height=12)
        data.append([name, f"{score:.1f}", bar, str(maxv)])

    table = Table(data, colWidths=[4.3 * cm, 1.8 * cm, 6.8 * cm, 1.5 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E0EF")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def _fmt_money(value):
    """Format a numeric value as Rs. X,XX,XXX"""
    try:
        n = int(float(value))
        # Indian numbering: last 3 then groups of 2
        s = str(n)
        if len(s) <= 3:
            return f"Rs. {s}"
        result = s[-3:]
        s = s[:-3]
        while s:
            result = s[-2:] + "," + result
            s = s[:-2]
        return f"Rs. {result}"
    except (TypeError, ValueError):
        return str(value)


def build_pdf_report(applicant: dict, result: dict, explanation_text: str,
                     applicant_name: str = "Applicant",
                     suggestions: list = None) -> bytes:
    buf = io.BytesIO()
    doc = BaseDocTemplate(buf, pagesize=A4,
                           leftMargin=1.8 * cm, rightMargin=1.8 * cm,
                           topMargin=2.6 * cm, bottomMargin=1.6 * cm)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_header_footer)])

    ss = _styles()
    story = []

    decision = result["decision"]
    decision_color = GREEN if decision == "Approved" else RED

    story.append(Paragraph("Loan Assessment Result", ss["VBTitle"]))
    story.append(Paragraph(f"Prepared for: {applicant_name}", ss["VBMuted"]))
    story.append(Spacer(1, 10))

    # Decision banner
    banner_data = [[
        Paragraph(f"<font color='white'><b>DECISION: {decision.upper()}</b></font>", ss["VBBody"]),
        Paragraph(f"<font color='white'>Confidence: {result['confidence']}%</font>", ss["VBBody"]),
        Paragraph(f"<font color='white'>ELRS Score: {result['elrs']['total']}/100 "
                  f"({result['elrs']['band']})</font>", ss["VBBody"]),
    ]]
    banner = Table(banner_data, colWidths=[6.2 * cm, 4.5 * cm, 6.2 * cm])
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), decision_color),
        ("VALIGN",    (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
    ]))
    story.append(banner)

    # ELRS pillar table
    story.append(Paragraph("Explainable Loan Risk Scoring (ELRS)", ss["VBSection"]))
    story.append(_pillar_bar_table(result["elrs"]))

    # Key contributing factors
    story.append(Paragraph("Key Contributing Factors", ss["VBSection"]))
    feat_data = [["Factor", "Effect"]]
    for f in result["top_features"]:
        effect = "(+) Positive" if f["impact"] > 0 else "(-) Negative"
        feat_data.append([f["feature"], effect])

    feat_table = Table(feat_data, colWidths=[9.4 * cm, 5.0 * cm])
    feat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), VIOLET),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR",  (1, 1), (1, -1), colors.black),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, VIOLET_LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E0EF")),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(feat_table)

    # AI explanation
    story.append(Paragraph("AI-Generated Explanation", ss["VBSection"]))
    story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#E2E0EF")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(explanation_text.replace("\n", "<br/>"), ss["VBBody"]))

    # Improvement suggestions
    if suggestions:
        story.append(Paragraph("Improvement Suggestions", ss["VBSection"]))
        story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#E2E0EF")))
        story.append(Spacer(1, 4))
        for i, tip in enumerate(suggestions, 1):
            story.append(Paragraph(f"{i}. {tip}", ss["VBTip"]))

    # Application summary — kept together to avoid mid-table page breaks
    summary_pairs = [
        ("Loan Purpose",         applicant.get("LoanPurpose", "-")),
        ("Loan Amount",          _fmt_money(applicant.get("LoanAmount"))),
        ("Loan Tenure (months)", str(int(float(applicant.get("LoanTenure", 0))))),
        ("Monthly Income",       _fmt_money(applicant.get("MonthlyIncome"))),
        ("Credit Score",         str(int(float(applicant.get("CreditScore", 0))))),
        ("Employment Type",      applicant.get("EmploymentType", "-")),
        ("Collateral Value",     _fmt_money(applicant.get("CollateralValue"))),
        ("Savings Balance",      _fmt_money(applicant.get("SavingsBalance"))),
    ]
    sdata = [[k, str(v)] for k, v in summary_pairs]
    stable = Table(sdata, colWidths=[6.0 * cm, 8.4 * cm])
    stable.setStyle(TableStyle([
        ("FONTSIZE",   (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR",  (0, 0), (0, -1), GREY),
        ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E2E0EF")),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))

    story.append(KeepTogether([
        Paragraph("Application Summary", ss["VBSection"]),
        Spacer(1, 4),
        stable,
    ]))

    doc.build(story)
    return buf.getvalue()
